myproject/coc/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: ivydong
# @Date:   2015-07-26 03:02:55
# @Last Modified time: 2015-07-27 11:43:13

from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^parse/$', views.parse_data, name='parse_data'),
]

myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from basic_search.models import *
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static
# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Influenza_NA
        fields = ('completeness', 'virus_name', 'date_discovered', 'age', 'genomesegment_or_proteinname' , 'subtype', 'host', 'gender', 'sequence_length', 'genbank_accession_number')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = Influenza_NA.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'nocoapi', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.


urlpatterns = [
    url(r'^', include('index.urls', namespace='index')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<username>\w+)/search/', include('basic_search.urls', namespace='basic_search')),
    url(r'^(?P<username>\w+)/', include('secure.urls', namespace='secure')),
    url(r'^(?P<username>\w+)/blast/', include('nocoblast.urls', namespace='nocoblast')),
    url(r'^(?P<username>\w+)/patientinfo/', include('patientinfo.urls', namespace='patientinfo')),
    url(r'^(?P<username>\w+)/graph/', include('graph.urls', namespace='graph')),
    url(r'^(?P<username>\w+)/search/details/matrix/', include('coc.urls', namespace='coc')),
    url(r'^(?P<username>\w+)/userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^(?P<username>\w+)/phylo/', include('treebuilder.urls', namespace='phylo')),
    url(r'^(?P<username>\w+)/api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] 

myproject/nocoblast/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',

    url(r'^blastn/', views.blastn, name="blastn"),
    url(r'^tblastn/', views.tblastn, name="tblastn"),
    url(r'^blast/$', views.blastn),
)

myproject/patientinfo/urls.py
from django.conf.urls import patterns, url, include

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mypatients/$', views.mypatients, name='mypatients'),
    url(r'^index_data/$', views.index_data, name='index_data'),
    url(r'^index_manage/$', views.index_manage, name='index_manage'),
    url(r'^(?P<patientinfo_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<patientinfo_id>[0-9]+)/update/$', views.update, name='update'),
    url(r'^(?P<patientinfo_id>[0-9]+)/uploaddata/$', views.uploaddata, name='uploaddata'),
    url(r'^(?P<patientinfo_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<patientinfo_id>[0-9]+)/viewdata/$', views.viewdata, name='viewdata'),
]

myproject/patientinfo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)


class Patientinfo(models.Model):
    firstname = models.CharField(max_length=20, null=False)
    lastname = models.CharField(max_length=20, null=False)
    date_of_birth = models.DateField(max_length=20, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    age = models.PositiveSmallIntegerField(null=True, blank=True)
    email = models.EmailField(max_length=50, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    street_address = models.CharField(max_length=20, null=True, blank=True)
    city = models.CharField(max_length=20, null=True, blank=True)
    provice = models.CharField(max_length=20, null=True, blank=True)
    postal_code = models.CharField(max_length=20, null=True, blank=True)
    patient_picture = models.FileField(upload_to="patient_picture/", blank=True, )
    patient_data = models.FileField(upload_to="patient_data/", blank=True, )
    doctor = models.ForeignKey(User, blank=True, null=True)

    def __str__(self):
        return self.firstname + " " + self.lastname

myproject/patientinfo/forms.py
from django import forms
from models import Patientinfo

class PatientinfoForm(forms.ModelForm):

        class Meta:
                model = Patientinfo
                fields = ('firstname',
                          'lastname',
                          'date_of_birth',
                          'gender',
                          'age',
                          'email',
                          'phone',
                          'street_address',
                          'city',
                          'provice',
                          'postal_code',
                          'patient_picture',
                          'patient_data',
                          'doctor',
                          )

class PatientDataForm(forms.ModelForm):


        class Meta:
                model = Patientinfo
                fields = ('patient_data',)

myproject/patientinfo/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from .models import *
from forms import PatientinfoForm
from forms import PatientDataForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.context_processors import csrf
from django.contrib.auth.models import User


# Create your views here.

@login_required
def index(request, username):
    return render(request, 'patientinfo/index.html', {'patientinfos': Patientinfo.objects.all(), 'username': username})

@login_required
def mypatients(request, username):
    patients = Patientinfo.objects.filter(doctor=request.user.id)
    return render(request, 'patientinfo/index.html', {'patientinfos': patients, 'username': username})


@login_required
def index_data(request, username):
    return render(request, 'patientinfo/index_data.html',
                  {'patientinfos': Patientinfo.objects.all(), 'username': username})


@login_required
def index_manage(request, username):
    return render(request, 'patientinfo/index_manage.html',
                  {'patientinfos': Patientinfo.objects.all(), 'username': username})


def detail(request, username, patientinfo_id):
    return render(request, 'patientinfo/detail.html',
                  {'patientinfo': Patientinfo.objects.get(id=patientinfo_id), 'username': username})


def create(request, username):
    if request.POST:
        form = PatientinfoForm(request.POST, request.FILES)
        if form.is_valid():
            form.cleaned_data['doctor'] = request.user.id
            form.save()

            return HttpResponseRedirect(reverse('patientinfo:index', kwargs={'username': username}))
    else:
        form = PatientinfoForm()

    args = {}
    args.update(csrf(request))

    args['form'] = form
    args['username'] = username
    return render(request, 'patientinfo/create.html', args)


def update(request, username, patientinfo_id):
    record = get_object_or_404(Patientinfo, id=patientinfo_id)

    if request.POST:
        form = PatientinfoForm(request.POST, request.FILES, instance=record)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('patientinfo:index', kwargs={'username': username}))
    else:
        form = PatientinfoForm(instance=record)

        args = {}
        args.update(csrf(request))

        args['form'] = form
        args['username'] = username
        args['patientinfo'] = Patientinfo.objects.get(id=patientinfo_id)
    return render(request, 'patientinfo/update.html', args)


def delete(request, username, patientinfo_id):
    record = Patientinfo.objects.get(id=patientinfo_id)
    record.delete()
    return render(request, 'patientinfo/delete.html', {'username': username})


def viewdata(request, username, patientinfo_id):
    return render(request, 'patientinfo/viewdata.html',
                  {'patientinfo': Patientinfo.objects.get(id=patientinfo_id), 'username': username})


def uploaddata(request, username, patientinfo_id):
    record = get_object_or_404(Patientinfo, id=patientinfo_id)

    if request.POST:
        form = PatientDataForm(request.POST, request.FILES, instance=record)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('patientinfo:index_data', kwargs={'username': username}))
    else:
        form = PatientDataForm(instance=record)

        args = {}
        args.update(csrf(request))

        args['form'] = form
        args['username'] = username
        args['patientinfo'] = Patientinfo.objects.get(id=patientinfo_id)
    return render(request, 'patientinfo/uploaddata.html', args)

myproject/patientinfo/templates/patientinfo/create.html
{% extends "secure/base.html" %}

{% block maincontent %}

</style>
    <!-- datepicker plugin site:http://jqueryui.com/datepicker/#dropdown-month-year-->
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_date_of_birth").datepicker({
                changeMonth: true,
                changeYear: true
            });
        });
    </script>

    <div class="row">

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Please fill patient information:</h1>
            </div>
        </div>

        {% if form.errors %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-warning">
                        <div class="panel-heading">Form Errors:</div>
                        <div class="panel-body">
                            <div class="row">
                                <p style="color: red;">
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            {{ field.html_name }}: {{ error|escape }}
                                            <br>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                            {{ field.html_name }}: {{ error|escape }}
                                        <br>
                                    {% endfor %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">Search:</div>
                    <div class="panel-body">

                        <div class="row">

                            <form id="search_form" class="form-horizontal"
                                  action="{% url 'patientinfo:create'  username %}" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.management_form }}

                                {% for field in form %}
                                    <div class="form-group">
                                        <label class="col-md-4 control-label" for="id_firstname">{{ field.label_tag }}</label>

                                        <div class="col-md-4">
                                            {{ field }}
                                        </div>
                                    </div>
                                {% endfor %}

                                <!-- Button -->
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="search"></label>

                                    <input class="btn btn-success btn-sm" id="search" type="submit" name="submit"
                                           value="Create Patient Information">
                                    <a href="{% url 'patientinfo:index'  username %}"><input
                                            class="btn btn-success btn-sm" value="Cancel"></a>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myproject/patientinfo/templates/patientinfo/detail.html
{% extends "secure/base.html" %}


{% block maincontent %}

<div class="row">
<br>
<br>
    <div class="col-md-5  toppad  pull-right ">
    </div>
    <div class="toppad">


        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Patient Info.</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <!-- display image  -->
                    {% if patientinfo.patient_picture %}
                        <div class="col-md-3 col-lg-3 " align="center"><img img
                                                                            src="/static/{{ patientinfo.patient_picture }}"
                                                                            class="img-circle img-responsive">
                        </div>
                    {% else %}
                        <div class="col-md-3 col-lg-3 " align="center"><p> No patient picture uploaded </p>
                        </div>
                    {% endif %}
                    <div class=" col-md-9 col-lg-9 ">
                        <table class="table table-striped">
                            <tbody>

                            <tr>
                                <td>First Name:</td>
                                <td>{{ patientinfo.firstname }}</td>
                            </tr>

                            <tr>
                                <td>Last Name:</td>
                                <td>{{ patientinfo.lastname }}</td>
                            </tr>

                            <tr>
                                <td>Date of Birth:</td>
                                <td>{{ patientinfo.date_of_birth }}</td>
                            </tr>

                            <tr>
                                <td>Gender:</td>
                                <td>{{ patientinfo.gender }}</td>
                            </tr>

                            <tr>
                                <td>Age:</td>
                                <td>{{ patientinfo.age }}</td>
                            </tr>

                            <tr>
                                <td>Email:</td>
                                <td>{{ patientinfo.email }}</td>
                            </tr>

                            <tr>
                                <td>Phone Number:</td>
                                <td>{{ patientinfo.phone }}
                                </td>
                            </tr>

                            <tr>
                                <td>Street Address:</td>
                                <td>{{ patientinfo.street_address }}
                                </td>
                            </tr>

                            <tr>
                                <td>City:</td>
                                <td>{{ patientinfo.city }}
                                </td>
                            </tr>

                            <tr>
                                <td>Provice:</td>
                                <td>{{ patientinfo.provice }}
                                </td>
                            </tr>

                            <tr>
                                <td>Postal Code:</td>
                                <td>{{ patientinfo.postal_code }}</td>
                            </tr>

                            <tr>
                                <td>Current Doctor:</td>
                                <td>{{ patientinfo.doctor }}</td>
                            </tr>


                            </tbody>
                        </table>

                        <a href="{% url 'patientinfo:viewdata' username patientinfo.id %}"
                           class="btn btn-primary">View Patient Data</a>

                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <a href="{% url 'patientinfo:index' username %}" class="btn btn-success btn-sm">Back to Patient
                    List</a>
                <span class="pull-right">
                    <a href="{% url 'patientinfo:update' username patientinfo.id %}"
                       class="btn btn-success btn-sm">Update</a>
                    <a href="{% url 'patientinfo:delete' username patientinfo.id %}"
                       class="btn btn-success btn-sm">Delete</a>
                </span>
            </div>

        </div>
    </div>
</div>
{% endblock %}

myproject/patientinfo/templates/patientinfo/index.html
{% extends "secure/base.html" %}


{% block maincontent %}

    <div class="row">

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Patient Information</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">Info:</div>
                    <div class="panel-body">

                        <div class="row">

                            {% if patientinfos %}
                                <a class="btn btn-success btn-large"  href="{% url 'patientinfo:create' username %}">Create New Patient Info</a>

                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Firstname</th>
                                        <th>Lastname</th>
                                        <th>Doctor</th>
                                        <th>Feature</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    {% for patientinfo in patientinfos %}
                                        <tr>
                                            <td>{{ patientinfo.firstname }}</td>
                                            <td>{{ patientinfo.lastname }}</td>
                                            <td>{{ patientinfo.doctor.username }}</td>
                                            <td><a href="{% url 'patientinfo:detail' username patientinfo.id %}"
                                                   class="btn btn-success btn-sm">View Patient detail</a></td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            {% else %}
                                <div id="noinfo">

                                    <p> You don't have any patient info yet, clicl the button to creat new </p>

                                    <a href="{% url 'patientinfo:create' username %}" class="btn btn-success btn-sm">Create
                                        New Patient Info</a>
                                </div>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myproject/patientinfo/templates/patientinfo/index_data.html
{% extends "secure/base.html" %}


    {% block maincontent%}
  

<div class="container">
  <h1>Patient Data</h1>

  {% if patientinfos %}
<li><a href="{% url 'patientinfo:create' username %}">Create New Patient Info</a></li>
          
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Feature</th>
      </tr>
    </thead>

    <tbody>
    {% for patientinfo in patientinfos %} 
      <tr>
        <td>{{ patientinfo.firstname }}</td>
        <td>{{ patientinfo.lastname }}</td>
        <td><a href="{% url 'patientinfo:viewdata' username patientinfo.id %}" class="btn btn-success btn-sm">View/Upload Patient Data</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div id="noinfo" >

  <p> You don't have any patient info yet, clicl the button to creat new </p>

  <a href="{% url 'patientinfo:create' username %}" class="btn btn-success btn-sm">Create New Patient Info</a>
  </div>
  {% endif %}
</div>

    {% endblock %}

myproject/patientinfo/templates/patientinfo/index_manage.html
{% extends "secure/base.html" %}


    {% block maincontent%}
  

<div class="container">
  <h1>Patient Management</h1>

  {% if patientinfos %}
<li><a href="{% url 'patientinfo:create' username %}">Create New Patient Info</a></li>
          
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Feature</th>
      </tr>
    </thead>

    <tbody>
    {% for patientinfo in patientinfos %} 
      <tr>
        <td>{{ patientinfo.firstname }}</td>
        <td>{{ patientinfo.lastname }}</td>
        <td><a href="{% url 'patientinfo:delete' username patientinfo.id %}" class="btn btn-success btn-sm">Delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  {% else %}
  <div id="noinfo" >

  <p> You don't have any patient info yet, clicl the button to creat new </p>

  <a href="{% url 'patientinfo:create' username %}" class="btn btn-success btn-sm">Create New Patient Info</a>
  </div>
  {% endif %}

</div>

    {% endblock %}

myproject/patientinfo/templates/patientinfo/mypatients.html
{% extends "secure/base.html" %}


{% block maincontent %}

    <div class="row">

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Current Patients under {{ username }}</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">Info:</div>
                    <div class="panel-body">

                        <div class="row">

                            {% if patientinfos %}
                                <a class="btn btn-success btn-large" href="{% url 'patientinfo:create' username %}">Create New Patient Info</a>

                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Firstname</th>
                                        <th>Lastname</th>
                                        <th>Feature</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    {% for patientinfo in patientinfos %}
                                        <tr>
                                            <td>{{ patientinfo.firstname }}</td>
                                            <td>{{ patientinfo.lastname }}</td>
                                            <td><a href="{% url 'patientinfo:detail' username patientinfo.id %}"
                                                   class="btn btn-success btn-sm">View Patient detail</a></td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            {% else %}
                                <div id="noinfo">

                                    <p> You don't have any patient info yet, clicl the button to creat new </p>

                                    <a href="{% url 'patientinfo:create' username %}" class="btn btn-success btn-sm">Create
                                        New Patient Info</a>
                                </div>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myproject/patientinfo/templates/patientinfo/update.html
{% extends "secure/base.html" %}
{% block maincontent %}

    <!-- datepicker plugin site:http://jqueryui.com/datepicker/#dropdown-month-year-->
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_date_of_birth").datepicker({
                changeMonth: true,
                changeYear: true
            });
        });
    </script>

    <div class="row">

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"> patient data:</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">Details:</div>
                    <div class="panel-body">

                        <div class="row">


                            <form action="{% url 'patientinfo:update'  username patientinfo.id %}" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                <table>
                                    {{ form.as_table }}
                                </table>

                                <div id="row">
                                    <input type="submit" name="submit" value="Update Patient Info"
                                           class="btn btn-success btn-large">
                                    <a href="{% url 'patientinfo:index'  username %}"
                                               class="btn btn-success btn-large">Cancel</a>
                                </div>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

myproject/patientinfo/templates/patientinfo/update_new.html
{% extends "secure/base.html" %}

{% block maincontent%}

<h2>Welcome: {{ user.username }}</h2>

<h3> Updating patient information:</h3>
<form id="search_form" class="form-horizontal" action="{% url 'patientinfo:update'  username patientinfo.id %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
 	<fieldset>
		<div class="form-group">
			<label class="col-md-4 control-label" for="id_firstname">Firstname:</label> 
	    	<div class="col-md-4">
				<input id="id_firstname" maxlength="20" name="firstname" type="text" placeholder="Enter Your First name" />

	  		</div>
	  	</div>
		
		<div class="form-group">
            <label class="col-md-4 control-label"  for="id_lastname">Lastname:</label>
            <div class="col-md-4">
				<input id="id_lastname" maxlength="20" name="lastname" type="text" placeholder="Enter Your Last name"/>

			</div>
		</div>
		
		<div class="form-group">
			<label class="col-md-4 control-label" for="id_date_of_birth">Date of birth:</label>
			<div class="col-md-4">
		 		<input id="id_date_of_birth" name="date_of_birth" type="text" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_gender">Gender:</label>
			<div class="col-md-4">
				<select id="id_gender" name="gender">
				<option value="" selected="selected">---------</option>
				<option value="M">Male</option>
				<option value="F">Female</option>
				
			</select>
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_age">Age:</label>
			<div class="col-md-4">
				<input id="id_age" min="0" name="age" type="number" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_email">Email:</label>
			<div class="col-md-4">
				<input id="id_email" maxlength="50" name="email" type="email" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_phone">Phone:</label>
			<div class="col-md-4">
				<input id="id_phone" maxlength="20" name="phone" type="text" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_street_address">Street address:</label>
			<div class="col-md-4">
				<input id="id_street_address" maxlength="20" name="street_address" type="text" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_city">City:</label>
			<div class="col-md-4">
				<input id="id_city" maxlength="20" name="city" type="text" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_provice">Provice:</label>
			<div class="col-md-4">
				<input id="id_provice" maxlength="20" name="provice" type="text" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_postal_code">Postal code:</label>
			<div class="col-md-4">
				<input id="id_postal_code" maxlength="20" name="postal_code" type="text" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_patient_picture">Uploade Patient Picture:</label>
			<div class="col-md-4">
				<input id="id_patient_picture"  name="patient_picture" type="file" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-4 control-label"  for="id_patient_data">Uploade Patient Data:</label>
			<div class="col-md-4">
				<input id="id_patient_data"  name="patient_data" type="file" />
			</div>
		</div>	

     	<!-- Button -->
		<div class="form-group">
            <label class="col-md-4 control-label" for="search"></label>
    
				<input class="btn btn-success btn-sm" id= "search" type= "submit"  name="submit" value="Update Patient Information">
			<a href="{% url 'patientinfo:index'  username %}"><input class="btn btn-success btn-sm" value="Cancel"></a>
		</div>

	</fieldset>
</form>

{% endblock %}

myproject/patientinfo/templates/patientinfo/uploaddata.html
{% extends "secure/base.html" %}
    {% block maincontent%}
<h1> Updating patient data</h1>

<form action="{% url 'patientinfo:uploaddata'  username patientinfo.id %}" method="post" enctype="multipart/form-data" >{% csrf_token %}
<ul>
	{{form.as_ul}}
</ul>

<input type= "submit"  name="submit" value="Update Patient Data" class="btn btn-success btn-sm">
</form>

<div id="sidebar">
	{% block sidebar %}
	<h2><a href="{% url 'patientinfo:index_data'  username %}"class="btn btn-success btn-sm">Cancel</a></h2>

	{% endblock %}
</div>
	

    {% endblock %}