myproject/coc/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: ivydong
# @Date:   2015-07-26 03:02:55
# @Last Modified time: 2015-07-27 11:43:13

from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^parse/$', views.parse_data, name='parse_data'),
]

myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from basic_search.models import *
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static
# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Influenza_NA
        fields = ('completeness', 'virus_name', 'date_discovered', 'age', 'genomesegment_or_proteinname' , 'subtype', 'host', 'gender', 'sequence_length', 'genbank_accession_number')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = Influenza_NA.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'nocoapi', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.


urlpatterns = [
    url(r'^', include('index.urls', namespace='index')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<username>\w+)/search/', include('basic_search.urls', namespace='basic_search')),
    url(r'^(?P<username>\w+)/', include('secure.urls', namespace='secure')),
    url(r'^(?P<username>\w+)/blast/', include('nocoblast.urls', namespace='nocoblast')),
    url(r'^(?P<username>\w+)/patientinfo/', include('patientinfo.urls', namespace='patientinfo')),
    url(r'^(?P<username>\w+)/graph/', include('graph.urls', namespace='graph')),
    url(r'^(?P<username>\w+)/search/details/matrix/', include('coc.urls', namespace='coc')),
    url(r'^(?P<username>\w+)/userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^(?P<username>\w+)/phylo/', include('treebuilder.urls', namespace='phylo')),
    url(r'^(?P<username>\w+)/api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] 

myproject/nocoblast/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',

    url(r'^blastn/', views.blastn, name="blastn"),
    url(r'^tblastn/', views.tblastn, name="tblastn"),
    url(r'^blast/$', views.blastn),
)

myproject/userprofile/urls.py
from django.conf.urls import url, patterns
from . import views

urlpatterns = [
	url(r'^setprofile/$', views.set_profile, name='setprofile'),
	url(r'^viewprofile/$', views.view_profile, name='viewprofile'),
]

myproject/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
       )

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    profile_picture = models.ImageField(upload_to='profile_picture', blank=True)
    address = models.CharField(max_length=50,null=True)
    phone = models.CharField(max_length=20, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True )
    def __unicode__(self):
        return self.user.username

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

myproject/userprofile/forms.py
from django import forms
from models import UserProfile

class UserProfileForm(forms.ModelForm):

  class Meta:
    model = UserProfile
    exclude = ('user',)

myproject/userprofile/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.core.context_processors import csrf
from forms import UserProfileForm

#Create your views here.

@login_required
def set_profile (request, username):
    
    if request. method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('userprofile:viewprofile', kwargs={'username': username}))
    else:
        
        user = request.user
        profile = user.profile
        form = UserProfileForm(instance = profile)

    args = {}
    args.update(csrf(request))

    args['form']=form 
    args['username']=username
    return render(request, 'userprofile/setprofile.html', args)


@login_required
def view_profile (request, username):
    profile = request.user.profile
    return render(request, 'userprofile/viewprofile.html', {'userprofile': profile,'username': username })
   

myproject/userprofile/templates/userprofile/setprofile.html
 {% extends "secure/base.html" %}
<style>
ul
{
list-style-type: none;
}

</style>
  {% block maincontent%}
  <h1>Welcome: {{ user.username }}</h1>
     <h2> Please Update Your Profile</h2>

     {% for field in form %}
        {{field.error}}

     {% endfor %}

    <form action="{% url 'userprofile:setprofile' username %}" method="post" enctype="multipart/form-data"> {% csrf_token %}

    <ul class="list-unstyled" style="font-size:12px;line-height: 4">
      <li>
        <label for="id_profile_picture">Profile picture:</label> 
        <input id="id_profile_picture" name="profile_picture" style="line-height:0.5;" type="file"></li>
      <li>
        <label for="id_address">Address:</label> 
        <input id="id_address" maxlength="50" name="address" style="line-height:2; width: 20em;" type="text"></li>
      <li>
        <label for="id_phone">Phone:&nbsp;&nbsp;&nbsp;</label> 
        <input id="id_phone" maxlength="20" name="phone" style="line-height:2;width: 20em;" type="text"></li>
      <li>
        <label for="id_gender">Gender:&nbsp;</label> 
        <select id="id_gender" name="gender">
          <option value="" selected="selected">---------</option>
          <option value="M">Male</option>
          <option value="F">Female</option>
        </select>
      </li>
    </ul>

    <input type="submit" value="Update" class="btn btn-success btn-sm">
  <a href="{% url 'userprofile:viewprofile'  username %}" style="margin-left:1em;" class="btn btn-success btn-sm">Cancle</a>
    </form>

  {% endblock %}

myproject/userprofile/templates/userprofile/viewprofile.html
{% extends "secure/base.html" %}


    {% block maincontent%}
<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
    

      </div>
        <div class="toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">User Profile</h3>
            </div>
            <div class="panel-body">
              <div class="row">
              <!-- display image  -->
                {% if userprofile.profile_picture %}
                <div class="col-md-3 col-lg-3 " align="center"> <img img src="/static/{{userprofile.profile_picture}}" class="img-circle img-responsive"> </div>
                {% else %}
                <div class="col-md-3 col-lg-3 " align="center"> <p> No user picture uploaded </p> </div>
                {% endif %}

                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-striped">
                    <tbody>
                       <tr>
                        <td>Username:</td>
                        <td>{{ userprofile.user.username }}</td>
                      </tr>
 
                      <tr>
                        <td>First Name:</td>
                        <td>{{ userprofile.user.first_name }}</td>
                      </tr>

                      <tr>
                        <td>Last Name:</td>
                        <td>{{ userprofile.user.last_name }}</td>
                      </tr>                  
                  
                         <tr>
                        <td>Gender:</td>
                        <td>{{ userprofile.gender }}</td>
                      </tr>

                      <tr>
                        <td>Email:</td>
                        <td>{{ userprofile.user.email }}</td>
                      </tr>

                      <tr>
                        <td>Phone Number:</td>
                        <td>{{ userprofile.phone }}
                        </td>
                      </tr>

                      <tr>
                        <td>Address:</td>
                        <td>{{ userprofile.address }}
                        </td>
                      </tr>

                   
                    </tbody>
                  </table>
                  
            
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                      <a href="{% url 'userprofile:setprofile' username %}" class="btn btn-success btn-sm">Setting Profile</a>
                        
                    </div>
            
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

myproject/userprofile/templates/userprofile/viewprofile_orig.html
{% extends "secure/base.html" %}


    {% block maincontent%}

<h1> User detial: </hi>

{% if userprofile.profile_picture %}
<p> User picture: </p>
<p><img src="/static/{{userprofile.profile_picture}}" width="200" /></p>
{% endif %}

<ul> 
	<li> Username: {{ userprofile.user.username }}</li>
	<li> First Name: {{ userprofile.user.first_name }}</li>
	<li> Last Name: {{ userprofile.user.last_name }}</li>
	<li> Gender: {{ userprofile.gender }}</li>
	<li> Phone: {{ userprofile.phone }}</li>
	<li> Email: {{ userprofile.user.email }}</li>
	<li> Address: {{ userprofile.address }}</li>


</ul>

<div id="sidebar"
	{% block sidebar %}
	<h2><a href="{% url 'userprofile:setprofile' username %}">Setting</a></h2>

	{% endblock %}
</div>

    {% endblock %}