myproject/coc/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: ivydong
# @Date:   2015-07-26 03:02:55
# @Last Modified time: 2015-07-27 11:43:13

from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^parse/$', views.parse_data, name='parse_data'),
]

myproject/index/urls.py
__author__ = 'Jeremy'


from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.indexview, name='index'),  # main index page.
    # url(r'^about/'), # about page.
    # url(r'^features/'), # features page.
    url(r'^login/$', views.loginview, name='login'),  #login page
    url(r'^logout/$', views.doctor_logout, name='logout'),  #logout page
    url(r'^login/verify/$', views.doctor_login, name='verifycredentials'),  # verify user
    #added by palmer,
    url(r'^register/$', views.doctor_register, name='register'),
    url(r'^register_success/$', views.doctor_register_success, name='register_success'),
    url(r'^data_graph/$', views.data_graph_json, name='data_graph_json'),
    url(r'^database_search/$', views.database_search, name='database_search'),
    url(r'^blast/$', views.blast, name='blast'),
    url(r'^phylip_intro/$', views.phylip_intro, name='phylip_intro'),
    url(r'^public_resource/symptoms/$', views.symptoms, name='symptoms'),
    url(r'^public_resource/cause/$', views.cause, name='cause'),
    url(r'^about/$', views.about, name='about'),
    url(r'^tutorial/$', views.tutorial, name='tutorial'),
    url(r'^website_intro/$', views.website_intro, name='website_intro'),
    url(r'^project/$', views.project_intro, name='project_intro'),
    url(r'^public_resource/transmission/$', views.transmission_type, name='transmission_type'),
    url(r'^public_resource/prevention/$', views.prevention, name='prevention'),
    url(r'^FAQs/$', views.FAQs, name='FAQs'),
    url(r'^contact_us/$', views.contact_us, name='contact_us'),
    url(r'^public_resource/$', views.public_resource, name='public_resource'),
]

myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from basic_search.models import *
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static
# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Influenza_NA
        fields = ('completeness', 'virus_name', 'date_discovered', 'age', 'genomesegment_or_proteinname' , 'subtype', 'host', 'gender', 'sequence_length', 'genbank_accession_number')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = Influenza_NA.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'nocoapi', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.


urlpatterns = [
    url(r'^', include('index.urls', namespace='index')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<username>\w+)/search/', include('basic_search.urls', namespace='basic_search')),
    url(r'^(?P<username>\w+)/', include('secure.urls', namespace='secure')),
    url(r'^(?P<username>\w+)/blast/', include('nocoblast.urls', namespace='nocoblast')),
    url(r'^(?P<username>\w+)/patientinfo/', include('patientinfo.urls', namespace='patientinfo')),
    url(r'^(?P<username>\w+)/graph/', include('graph.urls', namespace='graph')),
    url(r'^(?P<username>\w+)/search/details/matrix/', include('coc.urls', namespace='coc')),
    url(r'^(?P<username>\w+)/userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^(?P<username>\w+)/phylo/', include('treebuilder.urls', namespace='phylo')),
    url(r'^(?P<username>\w+)/api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] 

myproject/nocoblast/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',

    url(r'^blastn/', views.blastn, name="blastn"),
    url(r'^tblastn/', views.tblastn, name="tblastn"),
    url(r'^blast/$', views.blastn),
)

myproject/patientinfo/urls.py
from django.conf.urls import patterns, url, include

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mypatients/$', views.mypatients, name='mypatients'),
    url(r'^index_data/$', views.index_data, name='index_data'),
    url(r'^index_manage/$', views.index_manage, name='index_manage'),
    url(r'^(?P<patientinfo_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<patientinfo_id>[0-9]+)/update/$', views.update, name='update'),
    url(r'^(?P<patientinfo_id>[0-9]+)/uploaddata/$', views.uploaddata, name='uploaddata'),
    url(r'^(?P<patientinfo_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<patientinfo_id>[0-9]+)/viewdata/$', views.viewdata, name='viewdata'),
]

myproject/secure/urls.py
__author__ = 'Jeremy'


from django.conf.urls import url, patterns

from . import views

urlpatterns = [
    url(r'^$', views.indexview, name='index'),
]

myproject/userprofile/urls.py
from django.conf.urls import url, patterns
from . import views

urlpatterns = [
	url(r'^setprofile/$', views.set_profile, name='setprofile'),
	url(r'^viewprofile/$', views.view_profile, name='viewprofile'),
]

myproject/secure/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from patientinfo.models import Patientinfo
from basic_search.models import Influenza_AA, Influenza_NA
from nocoblast.models import FASTATable
import json


@login_required
def indexview(request, username):
    args = {}
    args['username'] = username
    args['mypatient_count'] = Patientinfo.objects.filter(doctor=request.user.id).count()
    args['database_entries'] = Influenza_AA.objects.all().count() + Influenza_NA.objects.all().count()
    args['blast_queries'] = FASTATable.objects.all().count()

    gender_donut = {}
    gender_donut['element'] = 'gender-moris-donut'
    gender_donut['data'] = []
    gender_donut['data'].append({'label': "Male", 'value': Patientinfo.objects.filter(gender='M').count()})
    gender_donut['data'].append({'label': "Female", 'value': Patientinfo.objects.filter(gender='F').count()})
    # gender_donut['data'][0]['label'] = 'Male'
    # gender_donut['data'][0]['value'] = Patientinfo.objects.filter(gender='M').count()
    # gender_donut['data'][1] = []
    # gender_donut['data'][1]['label'] = 'Female'
    # gender_donut['data'][1]['label'] = Patientinfo.objects.filter(gender='F').count()

    args['gender_donut'] = json.dumps(gender_donut)

    args['male_count'] = Patientinfo.objects.filter(gender='M').count()
    args['female_count'] = Patientinfo.objects.filter(gender='F').count()

    # Age metrics
    args['age1'] = Patientinfo.objects.filter(age__lte=10, age__gte=0).count()
    args['age2'] = Patientinfo.objects.filter(age__lte=20, age__gte=11).count()
    args['age3'] = Patientinfo.objects.filter(age__lte=30, age__gte=21).count()
    args['age4'] = Patientinfo.objects.filter(age__lte=40, age__gte=31).count()
    args['age5'] = Patientinfo.objects.filter(age__lte=50, age__gte=41).count()
    args['age6'] = Patientinfo.objects.filter(age__lte=60, age__gte=51).count()
    args['age7'] = Patientinfo.objects.filter(age__lte=70, age__gte=61).count()
    args['age8'] = Patientinfo.objects.filter(age__gte=71).count()


    # Host metrics
    args['host_human'] = Influenza_NA.objects.filter(host="Human").count() + Influenza_AA.objects.filter(
        host="Human").count()
    args['host_avian'] = Influenza_NA.objects.filter(host="Avian").count() + Influenza_AA.objects.filter(
        host="Avian").count()
    args['host_swine'] = Influenza_NA.objects.filter(host="Swine").count() + Influenza_AA.objects.filter(
        host="Swine").count()
    args['host_other'] = Influenza_NA.objects.all().count() + Influenza_AA.objects.all().count() - (
        args['host_human'] + args['host_avian'] + args['host_swine'])


    # Country Metrics
    args['country_count_NA'] = Influenza_NA.objects.values("country").annotate(Count("genbank_accession_number"))
    args['country_count_AA'] = Influenza_AA.objects.values("country").annotate(Count("genbank_accession_number"))

    return render(request, 'secure/index.html', args)

myproject/templates/secure/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NOSOCOMIAL INFECTIONS SURVEILLANCE SYSTEM</title>

    <!-- Java script -->
    <script type="text/javascript" src="{% static "jquery/dist/jquery.min.js" %}"></script>
    {#    <script src="{% static 'bootstrap-css/js/bootstrap.min.js' %}"></script>#}
    <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'metisMenu/dist/metisMenu.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'raphael/raphael-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'morrisjs/morris.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sb-admin-2.js' %}"></script>

    {% block javascript %}

    {% endblock %}

    <link type="text/css" href="{% static 'css/stickyfooter.css' %}" rel="stylesheet"/>
{#    <link href="{% static 'css/navbarstyle.css' %}" rel="stylesheet"/>#}
    <link type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'metisMenu/dist/metisMenu.min.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'css/timeline.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'morrisjs/morris.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;

      }

      {% block rawcss %}

      {% endblock %}


    </style>

    <!-- Link your style sheets here in your templates -->
    {% block css %}

    {% endblock %}

</head>
<body>

<div id="wrapper"><!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">

        {% include "secure/navigation.html" %}

    </nav>
</div>

<div id="wrapper"><!-- Main -->
    <div id="page-wrapper">

        <div class="container-fluid">
            {% block maincontent %}
                <!--maincontainer -->
            {% endblock %}
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        {% block documentready %}

        {% endblock %}

    });
</script>


<footer class="footer">
      <div class="container">

        {% include "secure/footer.html" %}

      </div>
</footer>


</body>
</html>

myproject/templates/secure/base_old.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NOSOCOMIAL INFECTIONS SURVEILLANCE SYSTEM</title>

    <link href="{% static 'bootstrap-css/css/bootstrap.min.css' %}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }

      {% block rawcss %}

      {% endblock %}
    </style>

    <!-- Link your style sheets here in your templates -->
    {% block css %}

    {% endblock %}
    <link href="{% static 'css/stickyfooter.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/navbarstyle.css' %}" rel="stylesheet"/>

    <!-- Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{% static 'bootstrap-css/js/bootstrap.min.js' %}"></script>

</head>
<body>
{% include "secure/menu.html" %}

<div id="wrap">
    <div class="container-fluid">
        {% block maincontent %}

        {% endblock %}
    </div> <!--maincontainer -->
</div>

{% include "secure/footer.html" %}

</body>
</html>

myproject/templates/secure/base_original.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NOSOCOMIAL INFECTIONS SURVEILLANCE SYSTEM</title>

    <link href="{% static 'bootstrap-css/css/bootstrap.min.css' %}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }

      {% block rawcss %}

      {% endblock %}
    </style>

    <!-- Link your style sheets here in your templates -->
    {% block css %}

    {% endblock %}
    <link href="{% static 'css/stickyfooter.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/navbarstyle.css' %}" rel="stylesheet"/>

    <!-- Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{% static 'bootstrap-css/js/bootstrap.min.js' %}"></script>

</head>
<body>
{% include "secure/menu.html" %}

<div id="wrap">
    <div class="container-fluid">
        {% block maincontent %}

        {% endblock %}
    </div> <!--maincontainer -->
</div>

{% include "secure/footer.html" %}

</body>
</html>

myproject/templates/secure/footer.html
{% block footer %}

{% endblock %}

myproject/templates/secure/navigation.html
{% load staticfiles %}
<!-- load js for navigation -->

<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <div class="logo pull-left">
        <a href="{% url 'secure:index' username %}" class=""><img src="{% static 'pic/log.png'%}" alt="NISS LOGO" style="margin-top:-10px;height:60px;width:60px;" ></a>
    </div>
    <a class="navbar-brand" href="{% url 'secure:index' username %}">NISS Portal</a>
</div>
<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right">
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="{% url 'userprofile:viewprofile' username %}"><i class="fa fa-user fa-fw"></i> User Profile</a>
            </li>
            <li><a href="{% url 'userprofile:setprofile' username %}"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li class="divider"></li>
            <li><a href="{% url 'index:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->


{#        ///////////////////////////////////////////////////////////////////////////////////////////////////////////#}


<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="{% url 'secure:index' username %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>

            <!-- Parient Info -->
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Patient Information<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{% url 'patientinfo:index'  username %}">General</a>
                    </li>
                    <li>
                        <a href="{% url 'patientinfo:mypatients' username %}">My Patients</a>
                    </li>
                    <li>
                        <a href="{% url 'patientinfo:create' username %}">Add Patient</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>

            <!--  -->
            <li>
                <a href="{% url 'basic_search:index' username %}"><i class="fa fa-table fa-fw"></i> Search Database </a>
            </li>
            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i> BLAST <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{% url 'nocoblast:tblastn' username %}">tBLASTn</a>
                    </li>
                    <li>
                        <a href="{% url 'nocoblast:blastn' username %}">BLASTn</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="{% url 'phylo:index' username %}"><i class="fa fa-edit fa-fw"></i> PhyloTree </a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->