myproject/coc/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: ivydong
# @Date:   2015-07-26 03:02:55
# @Last Modified time: 2015-07-27 11:43:13

from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^parse/$', views.parse_data, name='parse_data'),
]

myproject/index/urls.py
__author__ = 'Jeremy'


from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.indexview, name='index'),  # main index page.
    # url(r'^about/'), # about page.
    # url(r'^features/'), # features page.
    url(r'^login/$', views.loginview, name='login'),  #login page
    url(r'^logout/$', views.doctor_logout, name='logout'),  #logout page
    url(r'^login/verify/$', views.doctor_login, name='verifycredentials'),  # verify user
    #added by palmer,
    url(r'^register/$', views.doctor_register, name='register'),
    url(r'^register_success/$', views.doctor_register_success, name='register_success'),
    url(r'^data_graph/$', views.data_graph_json, name='data_graph_json'),
    url(r'^database_search/$', views.database_search, name='database_search'),
    url(r'^blast/$', views.blast, name='blast'),
    url(r'^phylip_intro/$', views.phylip_intro, name='phylip_intro'),
    url(r'^public_resource/symptoms/$', views.symptoms, name='symptoms'),
    url(r'^public_resource/cause/$', views.cause, name='cause'),
    url(r'^about/$', views.about, name='about'),
    url(r'^tutorial/$', views.tutorial, name='tutorial'),
    url(r'^website_intro/$', views.website_intro, name='website_intro'),
    url(r'^project/$', views.project_intro, name='project_intro'),
    url(r'^public_resource/transmission/$', views.transmission_type, name='transmission_type'),
    url(r'^public_resource/prevention/$', views.prevention, name='prevention'),
    url(r'^FAQs/$', views.FAQs, name='FAQs'),
    url(r'^contact_us/$', views.contact_us, name='contact_us'),
    url(r'^public_resource/$', views.public_resource, name='public_resource'),
]

myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from basic_search.models import *
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static
# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Influenza_NA
        fields = ('completeness', 'virus_name', 'date_discovered', 'age', 'genomesegment_or_proteinname' , 'subtype', 'host', 'gender', 'sequence_length', 'genbank_accession_number')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = Influenza_NA.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'nocoapi', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.


urlpatterns = [
    url(r'^', include('index.urls', namespace='index')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<username>\w+)/search/', include('basic_search.urls', namespace='basic_search')),
    url(r'^(?P<username>\w+)/', include('secure.urls', namespace='secure')),
    url(r'^(?P<username>\w+)/blast/', include('nocoblast.urls', namespace='nocoblast')),
    url(r'^(?P<username>\w+)/patientinfo/', include('patientinfo.urls', namespace='patientinfo')),
    url(r'^(?P<username>\w+)/graph/', include('graph.urls', namespace='graph')),
    url(r'^(?P<username>\w+)/search/details/matrix/', include('coc.urls', namespace='coc')),
    url(r'^(?P<username>\w+)/userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^(?P<username>\w+)/phylo/', include('treebuilder.urls', namespace='phylo')),
    url(r'^(?P<username>\w+)/api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] 

myproject/nocoblast/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',

    url(r'^blastn/', views.blastn, name="blastn"),
    url(r'^tblastn/', views.tblastn, name="tblastn"),
    url(r'^blast/$', views.blastn),
)

myproject/index/templates/index/FAQs.html
{% extends "public/base.html" %}
{% load staticfiles %}
{% block maincontent %}

	<style>
	li {
		
		font-size: 15px;
		text-decoration: none;
	line-height: 3;
	}
	h2 {
		font-size: 28px;
		line-height: 2;

	}
	</style>
	<div class="container">
		<section class="title-section">
		<h2>FAQs</h2>
		<ul class="breadcrumb breadcrumb__t" style="margin-bottom: 2em;">
		<li><a href="{% url 'index:index' %}">Home</a></li>
		<li class="divider"></li>
		<li class="active">FAQs</li>
		</ul></section>
		<div class="margin" style="margin-bottom: 150px;">
			<li> Who we are?</li>
				<p>We are Simon Fraser and Univeristy of British Columbia students.</p>
			<li> What is nosocomial infection?</li>
				<p>Please refer to <a href="{% url 'index:symptoms' %}">Everything about nosocomial infection. </a></p>
			<li> What is our project about? </li>
			<p>
			The goal would be to provide a nosocomial surveillance system in which infectious outbreaks in a hospital can be compared   and analysed against a database of catalogued pathogens in order to strive for an effective treatment against the infection. </p>
				<p>Pleae refer to <a href="{% url 'index:project_intro' %}">Discover Our Project.</a></p>
			<li> What technology do we implement in our website?</li>
			<div style="margin-left:2em;">
			<p>1. Django(https://www.djangoproject.com/)
			<p>Use the python framework django to build the main components of the application. These components will include:(1) a main front end, where the public will have  access to the main resources and database; (2) Interactive phylogenetic tree, where users are can interact with the cataloged bacterium; (3) a main administrator back end to update components in the front end.</p>
			<p>2. D3.js ​ (http://d3js.org/)</p>
			<p>The Javascript framework that will be used to create interactive charting diagrams.</p>
			<p>3. BLAST ​ (http://www.ncbi.nlm.nih.gov/books/NBK279690/)</p>
			<p>A command tool developed in by the NCBI that will be utilized when comparing or searching for a sequence of nucleotide base pairs or amino acids against the database of human microbiome DNA.</p>
			<p>4. PHYLIP​ (http://evolution.genetics.washington.edu/phylip.html)</p>
			A free package of programs to infer phylogenies with the help of genomic sequences.</p>
			<p>5. CLUSTALW2​ (http://helixweb.nih.gov/multi­align/man/clustalw.1.html)</p>
			<p>To carry out multiple sequence alignment of three or more biological sequences,generally protein, DNA, or RNA.</p>

			<p>6. MySQL ​ (https://www.mysql.com/)</p>
			<p>Use a database relational storage to hold relevant/persistent information for the web application and genome sequences.</p>

			<p>7. WSGI ​ (http://wsgi.readthedocs.org/en/latest/index.html)</p>
			<p>A python oriented ​ Web Server Gateway Interface.</p>

			<p>8. Apache ​ (http://httpd.apache.org/)</p>
			<p>A HTTP server used alongside WSGI through the module mod_wsgi that is provided by Apache.</p>
			</div>

			<li> How to use our website? </li>
				<p>PLease refer to <a href="{% url 'index:tutorial' %}">Live Tutorial.</a></p>
			<li> How to contact us?</li>
				<p>Please contact us via group9_470@gmail.com</p>
			<span style="float:right;"><img src="{% static "pic/faq.jpg" %}" style="height:200px;weigth:auto;" alt="FAQ"></span>
		</div>
	</div>

{% endblock %}

myproject/index/templates/index/about.html
{% extends "public/base.html" %}
{% load staticfiles %}
{% block maincontent %}
	<style>
	p{
	font-size: 15px;
	line-height: 2;
	text-decoration: none;
	}
	li {
		
		font-size: 15px;
		text-decoration: none;
		line-height: 2;
	}
	h2 {
		font-size: 28px;
		line-height: 2;

	}
	</style>

	<div class="container" style="height:100%;margin-bottom: 20em;">
		<div class="margin">
			<section class="title-section">
			<h2>NOSOCOMIAL INFECTION SURVEILLANCE SYSTEM</h2>
			<ul class="breadcrumb breadcrumb__t" style="margin-bottom: 2em;">
			<li><a href="{% url 'index:index' %}">Home</a></li>
			<li class="divider"></li>
			<li class="active">About</li>
			</ul></section>

			<p>Nosocomial infections are infections which are acquired in hospitals and other different healthcare facilities. According to the Centers for Disease Control and Prevention, in United States of America, about 1.7 million cases of such infections are reported every year, which prove to be fatal for about 99,000 deaths. Across the border, in Canada, about $1 billion is spent annually for treating these infections. An estimated 30% of nosocomial infections are preventable as per the Canadian Committee on Antibiotic Resistance. A total of five solutions have been talked about:</p>

			<p>More healthcare cleaning and infection control staff, with proper training and continuity.
			More rigorous cleaning and proper supplies
			Stop and reverse contracting-out
			Reduce occupancy rates
			Mandatory standards, monitoring and public reporting
			Here we present, NOSOCOMIAL INFECTION SURVEILLANCE SYSTEM which can be used as a detector tool and as an additional monitoring layer for reporting and predictive diagnosis of the nosocomial infections.</p>

			<p>This suite can be used for various purposes, by the doctors, researchers and patients for a wide range of applications, including:</p>
			<div style="margin-left:5em;">
			<li>Patient Information Management</li>
			<li>Read in the patient sequence data</li>
			<li>BLAST (Basic Local Alignment Search Tool) for finding strains which match the patient sequence.</li>
			<li>PHYLIP-TreeBuilder for finding the closest genetic relatives of the input sequence, builds up evolutionary relationship trees.</li>
			<li>TreeViewer- Visualize these evolutionary relationship trees, in different forms and analyze with all possible options.</li>
			<li>DataReporter- Visualize the sequence meta-data.</li>
			<li>Patient Result Viewer</li></div>
			<img src="{% static "pic/about.jpg" %}" style="weight:300px;height:300px;margin-left:60em;" alt="BLAST_screen">
		</div>
	</div>
</body>
{% endblock %}

myproject/index/templates/index/blast.html
{% extends "public/base.html" %}
    {% load staticfiles %}
  {% block maincontent %}
	 <style>
	p{
	font-size: 15px;
	line-height: 2;
	text-decoration: none;
	}
	li {
		
		font-size: 15px;
		text-decoration: none;
	line-height: 2;
	}
	h1,h2 {
		font-size: 28px;
		line-height: 2;

	}
	</style>
	<script type="text/javascript">
	<!--//
	function alert2()
	{
	alert ("Don't forget the curly "+
	"brackets - \nThey are essential!");
	}
	//-->
	</script>
	<div class="container">
		<div class="margin" style="margin-bottom: 200px;">
			<h2><img src="{% static "pic/blast.png" %}" style="height:50px;weigth:30px;margin-right: 20px;" alt="BLAST_LOGO">Basic Local Alignment Search Tool </h2>

			<p>In bioinformatics, BLAST for Basic Local Alignment Search Tool is an algorithm for comparing primary biological sequence information, such as the amino-acid sequences of different proteins or the nucleotides of DNA sequences. A BLAST search enables a researcher to compare a query sequence with a library or database of sequences, and identify library sequences that resemble the query sequence above a certain threshold.</p>

			<p>Different types of BLASTs are available according to the query sequences. For example, following the discovery of a previously unknown </p>

			<h2>Input</h2>
			<p>Input sequences (in FASTA or Genbank format) and weight matrix.</p>

			<h2>Output</h2>
			<p>BLAST output can be delivered in a variety of formats. These formats include HTML, plain text, and XML formatting. For NCBI's web-page, the default format for output is HTML. When performing a BLAST on NCBI, the results are given in a graphical format showing the hits found, a table showing sequence identifiers for the hits with scoring related data, as well as alignments for the sequence of interest and the hits received with corresponding BLAST scores for these. The easiest to read and most informative of these is probably the table.</p>

			<p>If one is attempting to search for a proprietary sequence or simply one that is unavailable in databases available to the general public through sources such as NCBI, there is a BLAST program available for download to any computer, at no cost. This can be found at BLAST+ executables. There are also commercial programs available for purchase. Databases can be found from the NCBI site, as well as from Index of BLAST databases (FTP).</p>
			<img src="{% static "pic/blast1.png" %}" alt="BLAST_screen">
			<img src="{% static "pic/blast2.png" %}" alt="BLAST_screen">
		</div>
	</div>


{% endblock %}

myproject/index/templates/index/contact_us.html
{% extends "public/base.html" %}
{% load staticfiles %}
{% block maincontent %}

<!-- Please run python manage.py migrate becasue it has model -->
<div class="container">
	<section class="title-section">
	<h2> Contact US </h2>
	<ul class="breadcrumb breadcrumb__t">
		<li><a href="{% url 'index:index' %}">Home</a></li>
		<li class="divider"></li>
		<li class="active">Contact Us</li>
	</ul>
	</p><address>
	<strong>8888 University Drive<br>
	Burnaby, B.C.<br>
	Canada. V5A 1S6</strong><br>
	Switchboard: +1 778.782.3111<br>
	Student Services: 778.782.6930<br>
	E-mail: <a href="mailto:sfucmpt470group09@gmail.com">sfucmpt470group09@gmail.com<script cf-hash="f9e31" type="text/javascript">
	/* <![CDATA[ */!function(){try{var t="currentScript"in document?document.currentScript:function(){for(var t=document.getElementsByTagName("script"),e=t.length;e--;)if(t[e].getAttribute("cf-hash"))return t[e]}();if(t&&t.previousSibling){var e,r,n,i,c=t.previousSibling,a=c.getAttribute("data-cfemail");if(a){for(e="",r=parseInt(a.substr(0,2),16),n=2;a.length-n;n+=2)i=parseInt(a.substr(n,2),16)^r,e+=String.fromCharCode(i);e=document.createTextNode(e),c.parentNode.replaceChild(e,c)}}}catch(u){}}();/* ]]> */</script></a><br>
	</address> 

	<div class="container" style="margin-bottom: 200px;">
	<form name="myform" action ="{% url 'index:contact_us' %}" method="POST"> {% csrf_token %}
		<p>
			<input id="name" style="width:31%;margin-right:30px;" name="name"  type="text" placeholder="Name" required/>
			<input id="email" name="email" style="width:31%; margin-right:15px;" type="email" placeholder="Email" required/>
			<input id="phone" name="phone"  style="width:31%;margin-left:15px;" type="text" placeholder="Phone" required/>
		</p>
		<p><textarea id="message" name="message" type="text" placeholder="Message" required></textarea></p>
		<p><input class="btn btn-success btn-sm"  type= "submit"  value="Submit" name="submit" /></p>
	</form>
	</div>
	</div>

{% endblock %}

myproject/index/templates/index/login.html
{% extends "public/base.html" %}

{% block maincontent%}
  <div class="container">
    <form  method="post" action="{% url 'index:verifycredentials' %}">
        {% csrf_token %}
        <fieldset style="margin-bottom:600px;" >

        <!-- Form Name -->
        <legend>Login:</legend>

        <!-- Text input-->
        <div class="form-group">
          <label class="col-md-4 control-label" for="username">Username</label>
          <div class="col-md-4">
          <input id="username" name="username" type="text" placeholder="Username" class="form-control input-md" required="">
          <span class="help-block">* Your username. </span>
          </div>
        </div>

        <!-- Password input-->
        <div class="form-group">
          <label class="col-md-4 control-label" for="password">Password</label>
          <div class="col-md-4">
            <input id="password" name="password" type="password" placeholder="Password" class="form-control input-md" required="">
            <span class="help-block">* Enter in the password the administrator has provided. </span>
          </div>
        </div>

        <!-- Button -->
        <div class="form-group">
          <label class="col-md-4 control-label" for="submit"></label>
          <div class="col-md-4">
            <input type="submit" name="submit" value="Login" class="btn btn-primary"/>
          </div>
        </div>
        <!-- Added by palmer -->
        <div class="form-group">
          <label class="col-md-4 control-label" for="submit"></label>
          <div class="col-md-4" style="font-size:14px; line-height:3;">  
            <a href="{% url 'index:register' %}"> New customer? Please register an account.</a>
          </div>
        </div>
        </fieldset>
    </form>
  </div>
{% endblock %}

myproject/index/templates/index/phylip_intro.html
{% extends "public/base.html" %}
{% load staticfiles %}
{% block maincontent %}
	<style>
	p{
	font-size: 15px;
	line-height: 2;
	text-decoration: none;
	}
	li {
		
		font-size: 15px;
		text-decoration: none;
	line-height: 2;
	}
	h2 {
		font-size: 28px;
		line-height: 3;

	}
	</style>
	<div class="container">
		<div class="margin" style="margin-bottom: 150px;">
			<h2><img src="{% static "pic/phylip.gif" %}" style="height:60px;weigth:auto;margin-right: 20px;" alt="PHYLIP_TREE">PHYLOGENIES EVOLUTION TREE </h2>
			<img src="{% static "pic/tree.png" %}" alt="Phylip_tree"/> 
			<p>PHYLIP  is a package of programs for inferring phylogenies (evolutionary trees). It is available free over the Internet, and written to work on as many different kinds of computer systems as possible. The source code is distributed (in C), and executables are also distributed. In particular, already-compiled executables are available for Windows (95/98/NT/2000/me/xp/Vista), Mac OS X, and Linux systems. Older executables are also available for Mac OS 8 or 9 systems. Complete documentation is available on documentation files that come with the package.</p>

			<p>Methods that are available in the package include parsimony, distance matrix, and likelihood methods, including bootstrapping and consensus trees. Data types that can be handled include molecular sequences, gene frequencies, restriction sites and fragments, distance matrices, and discrete characters.</p>

			<p>The programs are controlled through a menu, which asks the users which options they want to set, and allows them to start the computation. The data are read into the program from a text file, which the user can prepare using any word processor or text editor (but it is important that this text file not be in the special format of that word processor -- it should instead be in "flat ASCII" or "Text Only" format). Some sequence analysis programs such as the ClustalW alignment program can write data files in the PHYLIP format. Most of the programs look for the data in a file called "infile" -- if they do not find this file they then ask the user to type in the file name of the data file.</p>

			<p>Output is written onto special files with names like "outfile" and "outtree". Trees written onto "outtree" are in the Newick format, an informal standard agreed to in 1986 by authors of a number of major phylogeny packages.</p>
			<img src="{% static "pic/phylo1.png" %}" alt="Phylip_tree"/> 
			<img src="{% static "pic/phylo2.png" %}" alt="Phylip_tree"/> 
			<img src="{% static "pic/phylo3.png" %}" alt="Phylip_tree"/> 
		</div>

	</div>
{% endblock %}

myproject/index/templates/index/public_1.html
{% extends "public/base.html" %}

{% block maincontent%}
{% load staticfiles %}

  <style>
  .demo { width:400px; float:left; }
  .contenthover { padding:20px 20px 20px 20px; }
  .contenthover, .contenthover h3, contenthover a { color:#fff; }
  .contenthover h3, .contenthover p , .contenthover li { margin:3em 0 1em 1em; line-height:1.4em; padding:0; }
  .contenthover a.mybutton { display:block; float:left; margin-left: 50px; margin-top:20px; padding:10px 10px; background:#3c9632; color:#fff; -moz-border-radius: 5px; -webkit-border-radius: 4px; border-radius: 4px; }
  .contenthover a.mybutton:hover { background:#34742d }
  .body{
  font-size: 18px;
  line-height: 2;
  font-family: Helvetica, Arial, sans-serif;
  padding-left: 100px;
  padding-top: 150px;

  }
  h3 {

    margin-top:40px;
  }
  </style>


  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>

  <script>
  /*!
   * ContentHover jQuery plugin v0.1
   * http://www.backslash.gr/demos/contenthover-jquery-plugin/
   *
   * Copyright 2011 by Nikos Tsaganos
   * http://www.backslash.gr/
   */
  (function($){var methods={init:function(options){var defaults={data_selector:'.contenthover',width:0,height:0,overlay_width:0,overlay_height:0,overlay_x_position:'center',overlay_y_position:'bottom',overlay_background:'',overlay_opacity:1,effect:'fade',fade_speed:400,slide_speed:400,slide_direction:'bottom',zindex:2,wrapper_class:'ch_wrapper',normal_class:'ch_normal',hover_class:'ch_hover',onshow:function(){},onhide:function(){}},settings=$.extend({},defaults,options);return this.each(function(){var $this=$(this),w=$this.width()?$this.width():settings.width,h=$this.height()?$this.height():settings.height,overlay_w=settings.overlay_width?settings.overlay_width:w,overlay_h=settings.overlay_height?settings.overlay_height:h,$data=$this.next(settings.data_selector);if($data.length){$data.hide();var $ch_wrapper=$('<div>').addClass('ch_element').addClass(settings.wrapper_class).css({'width':w,'height':h,'position':'relative','overflow':'hidden'}).insertAfter($this);var $ch_normal=$('<div>').addClass(settings.normal_class).css({'width':w,'height':h,'position':'absolute','z-index':settings.zindex}).appendTo($ch_wrapper);$this.clone().appendTo($ch_normal);$this.hide();var $ch_hover=$('<div>').addClass(settings.hover_class).css({'width':overlay_w,'height':overlay_h,'position':'absolute','z-index':settings.zindex-1}).appendTo($ch_wrapper);$data.clone().show().appendTo($ch_hover);var ch_hover_css={};if(settings.overlay_background){ch_hover_css.background=settings.overlay_background;}
  if(settings.overlay_opacity<1){ch_hover_css.opacity=settings.overlay_opacity;}
  if(settings.overlay_x_position=='left'){ch_hover_css.left=0;}else if(settings.overlay_x_position=='right'){ch_hover_css.left=(w-overlay_w)+'px';}else{ch_hover_css.left=(w/2-overlay_w/2)+'px';}
  if(settings.overlay_y_position=='top'){ch_hover_css.top=0;}else if(settings.overlay_y_position=='bottom'){ch_hover_css.top=(h-overlay_h)+'px';}else{ch_hover_css.top=(h/2-overlay_h/2)+'px';}
  $ch_hover.css(ch_hover_css);if(settings.effect=='slide'){var initial_css={};if(settings.slide_direction=='top'){initial_css={top:('-'+overlay_h+'px')};}
  if(settings.slide_direction=='bottom'){initial_css={top:h+'px'};}
  if(settings.slide_direction=='left'){initial_css={left:('-'+overlay_w+'px')};}
  if(settings.slide_direction=='right'){initial_css={left:w+'px'};}
  $ch_hover.css('z-index',settings.zindex+1).css(initial_css);$ch_wrapper.hover(function(){$ch_hover.stop(true,true).animate({'top':ch_hover_css.top,'left':ch_hover_css.left},settings.slide_speed,settings.onshow());},function(){$ch_hover.stop(true,true).animate(initial_css,settings.slide_speed,settings.onhide());});}else if(settings.effect=='fade'){$ch_hover.css('z-index',settings.zindex+1).hide();$ch_wrapper.hover(function(){$ch_hover.stop(true,true).fadeIn(settings.fade_speed,settings.onshow());},function(){$ch_hover.stop(true,true).fadeOut(settings.fade_speed,settings.onhide());});}else{$ch_hover.css('z-index',settings.zindex+1).hide();$ch_wrapper.hover(function(){$ch_hover.show(0,settings.onshow());},function(){$ch_hover.hide(0,settings.onhide());});}}});},stop:function(){return this.each(function(){var $this=$(this),$data=$this.next('.ch_element');$this.show();$data.remove();$this.unbind('.contenthover');});},destroy:function(){return this.each(function(){$(this).show();$('.ch_element').remove();$(window).unbind('.contenthover');});}};$.fn.contenthover=function(method){if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method==='object'||!method){return methods.init.apply(this,arguments);}else{$.error('Method '+method+' does not exist in contentHover plugin.');}};})(jQuery);
  </script>

  <script>
    $(function(){
      $('#d1').contenthover({
        overlay_background:'#000',
        overlay_opacity:0.8
      });
    });
    $(function(){
      $('#d2').contenthover({
        overlay_background:'#000',
        overlay_opacity:0.8
      });
    });
  $(function(){
      $('#d3').contenthover({
        overlay_background:'#000',
        overlay_opacity:0.8
      });
    });
  $(function(){
      $('#d4').contenthover({
        overlay_background:'#000',
        overlay_opacity:0.8
      });
    });
  $(function(){
      $('#d5').contenthover({
        overlay_background:'#000',
        overlay_opacity:0.8
      });
    });

  </script>

  <div class="body">
     <div class="demo" style="margin-bottom: 200px;">
            <img id="d1" src="{% static 'pic/1.PNG' %}" />
            <div class="contenthover">
              <h3>SYMPTOMS</h3>
              <li>Pain</li>
              <li>Fever</li>
              <li>Night Sweats</li>
              <li>Infection</li>

              <p><a href="{% url 'index:symptoms' %}" class="mybutton">Click to read more !</a></p>
            </div>
      </div>
       <div class="demo">
            <img id="d2" src="{% static 'pic/3.PNG' %}" />
            <div class="contenthover">
              <h3>TRANSMISSION</h3>
              <p>Main transmission channle incudes:</p>
              <li>Contact Transmission</li>
              <li>Vehicle Transmission</li>
              <li>Vector Transmission</li>
              <p><a href="{% url 'index:transmission_type' %}" class="mybutton">Click to read more !</a></p>
            </div>
      </div>
          <div class="demo">
            <img id="d3" src="{% static 'pic/4.PNG' %}" />
            <div class="contenthover">
              <h3>PREVENTION</h3>
                <li>Isolation</li>
                <li>Clean Environment</li>
                  <li>Food and Water Procution</li>
                  <li>Education</li>
                  <p><a href="{% url 'index:prevention' %}" class="mybutton">Click to read more !</a></p>
            </div>
      </div>
           <div class="demo">
            <img id="d4" src="{% static 'pic/2.PNG' %}" />
            <div class="contenthover">
              <h3>STATISTICS</h3>
              <p>Graph 1: Healthcare-associated MRSA rates per 1,000 patient admissions from 1995 to 2009, Canada</p>
              <p>Graph 2:Estimates of Healthcare-Associated Infections Occurring in Acute Care Hospitals in the United States, 2011</p>
              <p><a href="{% url 'index:cause' %}" class="mybutton">Click to read more !</a></p>
            </div>
      </div>
  </div>
{% endblock %}

myproject/index/templates/index/register_success.html
{% extends "public/base.html" %}

{% block maincontent%}
	<div class="container" style="margin-bottom: 650px;">
		<h2> You have registered!</h2>
		<P>Click <a href="{% url 'index:login' %}">here </a> to login again </P>
	</div>
{% endblock %}

myproject/index/templates/index/tutorial.html
{% load staticfiles %}
<img src="{% static "pic/out1.gif" %}"  style="height:600px;width:auto;" alt="database_screen"/>